In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
## sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',

]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
#3 Define the vocabulary size
voc_size=10000


In [ ]:
# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.utils import pad_sequences
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Embedding

# texts = ["I love AI", "AI is future"]

# tokenizer = Tokenizer()
# tokenizer.fit_on_texts(texts)

# sequences = tokenizer.texts_to_sequences(texts)

# padded = pad_sequences(sequences, maxlen=5)

# model = Sequential()
# model.add(Embedding(input_dim=1000, output_dim=64, input_length=5))

In [ ]:
### One hot Representation
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[4387, 1361, 1957, 5137],
 [4387, 1361, 1957, 5353],
 [4387, 5816, 1957, 8045],
 [7210, 6657, 8738, 9776, 2893],
 [7210, 6657, 8738, 9776, 5223],
 [4616, 4387, 4784, 1957, 4064],
 [865, 1581, 2154, 9776]]

In [ ]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
# Embedding(input_dim, output_dim, input_length)
# input_dim → vocabulary size  ..number of unique words your model can handle.
# output_dim → vector size (e.g., 50, 100, 300)
# input_length →   Length of each input sequence after padding

#from tesnsorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4387 1361 1957 5137]
 [   0    0    0    0 4387 1361 1957 5353]
 [   0    0    0    0 4387 5816 1957 8045]
 [   0    0    0 7210 6657 8738 9776 2893]
 [   0    0    0 7210 6657 8738 9776 5223]
 [   0    0    0 4616 4387 4784 1957 4064]
 [   0    0    0    0  865 1581 2154 9776]]


In [ ]:
## feature representation
dim=10


In [ ]:
from tensorflow.keras.layers import Input

In [ ]:
model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))

model.compile(optimizer='adam', loss='mse')

In [ ]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step


array([[[ 0.02214679, -0.02807356, -0.02002709,  0.01313518,
         -0.04894378,  0.03023434, -0.03893539,  0.01090878,
         -0.02398872,  0.01564643],
        [ 0.02214679, -0.02807356, -0.02002709,  0.01313518,
         -0.04894378,  0.03023434, -0.03893539,  0.01090878,
         -0.02398872,  0.01564643],
        [ 0.02214679, -0.02807356, -0.02002709,  0.01313518,
         -0.04894378,  0.03023434, -0.03893539,  0.01090878,
         -0.02398872,  0.01564643],
        [ 0.02214679, -0.02807356, -0.02002709,  0.01313518,
         -0.04894378,  0.03023434, -0.03893539,  0.01090878,
         -0.02398872,  0.01564643],
        [-0.03208714,  0.0067706 ,  0.04018507,  0.01643643,
         -0.0399287 , -0.03925725, -0.01700524,  0.03557167,
          0.04772795,  0.03120803],
        [-0.04170961,  0.02150687,  0.03691341, -0.02643988,
          0.02806318,  0.00424599, -0.02806144,  0.02650056,
         -0.02499112, -0.03547883],
        [-0.00625778, -0.02802063,  0.00017269,  0.0